COMPILER=g++
FLAGS=-g -std=c++11
FILES=utils.cpp process.cpp ../core/process/Process.cpp ../core/util/file.c ../core/sys/SystemInfo.cpp ../core/sys/SystemUser.cpp ../core/util/str.cpp
EXECUTABLE=tests

all:
	$(COMPILER) $(FLAGS) $(FILES) -o $(EXECUTABLE)
